routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'namespace' => 'App\Http\Controllers',
], function () {
    Route::get('/blog/category/{slug?}', 'BlogController@category')->name('category');
    Route::get('/blog/article/{slug?}', 'BlogController@article')->name('article');
});

Route::get('/', function () {
    return view('blog.home');
});

Auth::routes();

Route::group([
  'prefix' => 'admin',
  'namespace' => 'App\Http\Controllers\Admin',
  'middleware' => ['auth']
], function () {
   Route::get('/', 'DashboardController@dashboard')->name('admin.index');
   Route::resource('category', 'CategoryController', ['as' => 'admin']);
   Route::resource('article', 'ArticleController', ['as' => 'admin']);

   Route::group([
       'prefix' => 'user_management',
       'namespace' => 'UserManagement',
   ], function() {
       Route::resource('user', 'UserController', ['as' => 'admin.user_management']);
   });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/UserManagement/UserController.php
<?php

namespace App\Http\Controllers\Admin\UserManagement;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.user_management.users.index', [
            'users' => User::paginate(10),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user_management.users.create', [
            'user' => [],
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);

        User::create([
            'name' => $request['name'],
            'email' => $request['email'],
            'password' => bcrypt($request['password']),
        ]);

        return redirect()->route('admin.user_management.user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.user_management.users.edit', [
            'user' => $user,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $validator = $request->validate([
            'name' => ['required', 'string', 'max:255'],
            'email' => [
                'required',
                'string',
                'email',
                'max:255',
                // проверяю, что такого же email нет среди других пользователей
                \Illuminate\Validation\Rule::unique('users')->ignore($user->id),
                ],
            'password' => ['nullable', 'string', 'min:8', 'confirmed'],
        ]);

        $user->name = $request['name'];
        $user->email = $request['email'];
        $request['password'] == null ?: $user->password = bcrypt($request['password']);
        $user->save();

        return redirect()->route('admin.user_management.user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        return redirect()->route('admin.user_management.user.index');
    }
}

resources/views/admin/user_management/users/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')
<div class="container">
  @component('admin.components.breadcrumb')
    @slot('title') Создание пользователя @endslot
    @slot('parent') Главная @endslot
    @slot('active') Пользователь @endslot
  @endcomponent

  <hr>

  <form action="{{route('admin.user_management.user.store')}}" method="POST" class="form-horizontal">
    {{ csrf_field() }}

    @include('admin.user_management.users.partials.form')

  </form>
</div>
@endsection

resources/views/admin/user_management/users/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')
<div class="container">
  @component('admin.components.breadcrumb')
    @slot('title') Редактирование пользователя @endslot
    @slot('parent') Главная @endslot
    @slot('active') Пользователь @endslot
  @endcomponent

  <hr>

  <form action="{{route('admin.user_management.user.update', $user)}}" method="POST" class="form-horizontal">
    @method('PUT')
    {{ csrf_field() }}

    @include('admin.user_management.users.partials.form')
  </form>
</div>
@endsection

resources/views/admin/user_management/users/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')

<div class="container">
  @component('admin.components.breadcrumb')
    @slot('title') Список пользователей @endslot
    @slot('parent') Главная @endslot
    @slot('active') Пользователи @endslot
  @endcomponent

  <hr>

  <a href="{{route('admin.user_management.user.create')}}" class="btn btn-primary float-end">
    <i class="fa fa-plus"></i>
    Создать пользователя
  </a>

  <table class="table">
    <thead>
      <th>Имя</th>
      <th>Email</th>
      <th class="text-right">Действие</th>
    </thead>
    <tbody>
      @forelse ($users as $user)
        <tr>
          <td>{{$user->name}}</td>
          <td>{{$user->email}}</td>
          <td class="float-end">
            <form class="form-horizontal" onsubmit="return confirm('Удалить пользователя?')" action="{{route('admin.user_management.user.destroy', $user)}}" method="post">
              @method('DELETE')
              @csrf

              <a class="btn btn-outline-dark" href="{{route('admin.user_management.user.edit', $user)}}"><i class="fa fa-edit"></i></a>
              <button class="btn btn-outline-danger" type="submit" name="button"><i class="fa fa-trash"></i></button>
            </form>
          </td>
        </tr>
      @empty
        <tr>
          <td colspan="3" class="text-center"><h2>Данные отсутствуют</h2></td>
        </tr>
      @endforelse
    </tbody>
    <tfoot>
      <tr>
        <td colspan="3">
          <ul class="pagination float-end">
            {{$users->links()}}
          </ul>
        </td>
      </tr>
    </tfoot>
  </table>
</div>

@endsection