routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([
    'namespace' => 'App\Http\Controllers',
], function () {
    Route::get('/blog/category/{slug?}', 'BlogController@category')->name('category');
    Route::get('/blog/article/{slug?}', 'BlogController@article')->name('article');
});

Route::get('/', function () {
    return view('blog.home');
});

Auth::routes();

Route::group([
  'prefix' => 'admin',
  'namespace' => 'App\Http\Controllers\Admin',
  'middleware' => ['auth']
], function () {
   Route::get('/', 'DashboardController@dashboard')->name('admin.index');
   Route::resource('category', 'CategoryController', ['as' => 'admin']);
   Route::resource('article', 'ArticleController', ['as' => 'admin']);

   Route::group([
       'prefix' => 'user_management',
       'namespace' => 'UserManagement',
   ], function() {
       Route::resource('user', 'UserController', ['as' => 'admin.user_management']);
   });
});

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Article extends Model
{
    use HasFactory;

    protected $fillable = [
      'published',
      'title',
      'slug',
      'description_short',
      'description',
      'image',
      'image_show',
      'meta_title',
      'meta_description',
      'meta_keywords',
      'views',
      'created_by',
      'modified_by',
    ];

    public function setSlugAttribute($value) {
      $this->attributes['slug'] = Str::slug(mb_substr($this->title, 0, 40) . "-" . \Carbon\Carbon::now()->format('dmyHi'), '-');
    }

    // полиморфная связь с категориями
    public function categories() {
      return $this->morphToMany(Category::class, 'categoryable');
    }

    // получение определенного количества последних созданных статей
    public function scopeLastArticles($query, $count) {
      return $this->orderBy('created_at', 'desc')->take($count)->get();
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Article;
use App\Models\Category;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.articles.index', [
          'articles' => Article::orderBy('created_by', 'desc')->paginate(10)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.articles.create', [
          'article' => [],
          'categories' => Category::with('children')->where('parent_id', 0)->get(),
          'delimiter' => ''
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $article = Article::create($request->all());

        if ($request->input('categories')) {
          $article->categories()->attach($request->input('categories'));
        }

        return redirect()->route('admin.article.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        return view('admin.articles.edit', [
          'article' => $article,
          'categories' => Category::with('children')->where('parent_id', 0)->get(),
          'delimiter' => ''
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Article $article)
    {
        $article->categories()->detach();

        if ($request->input('categories')) {
          $article->categories()->attach($request->input('categories'));
        }

        $article->update($request->except('slug'));

        return redirect()->route('admin.article.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        $article->categories()->detach();
        $article->delete();

        return redirect()->route('admin.article.index');
    }
}

resources/views/admin/articles/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')
<div class="container">
  @component('admin.components.breadcrumb')
    @slot('title') Создание статьи @endslot
    @slot('parent') Главная @endslot
    @slot('active') Статьи @endslot
  @endcomponent

  <hr>

  <form action="{{route('admin.article.store')}}" method="POST" class="form-horizontal">
    {{ csrf_field() }}

    @include('admin.articles.partials.form')

    <input type="hidden" name="created_by" value="{{Auth::id()}}">
  </form>
</div>
@endsection

resources/views/admin/articles/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')
<div class="container">
  @component('admin.components.breadcrumb')
    @slot('title') Редактирование статьи @endslot
    @slot('parent') Главная @endslot
    @slot('active') Статьи @endslot
  @endcomponent

  <hr>

  <form action="{{route('admin.article.update', $article)}}" method="POST" class="form-horizontal">
    @method('PUT')
    {{ csrf_field() }}

    @include('admin.articles.partials.form')

    <input type="hidden" name="modified_by" value="{{Auth::id()}}">
  </form>
</div>
@endsection

resources/views/admin/articles/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')

<div class="container">
  @component('admin.components.breadcrumb')
    @slot('title') Список статей @endslot
    @slot('parent') Главная @endslot
    @slot('active') Статьи @endslot
  @endcomponent

  <hr>

  <a href="{{route('admin.article.create')}}" class="btn btn-primary float-end">
    <i class="fa fa-plus"></i>
    Создать статью
  </a>

  <table class="table">
    <thead>
      <th>Наименование</th>
      <th>Публикация</th>
      <th class="text-right">Действие</th>
    </thead>
    <tbody>
      @forelse ($articles as $article)
        <tr>
          <td>{{$article->title}}</td>
          <td>{{$article->published}}</td>
          <td class="float-end">
            <form class="form-horizontal" onsubmit="return confirm('Удалить статью?')" action="{{route('admin.article.destroy', $article)}}" method="post">
              @method('DELETE')
              @csrf

              <a class="btn btn-outline-dark" href="{{route('admin.article.edit', $article)}}"><i class="fa fa-edit"></i></a>
              <button class="btn btn-outline-danger" type="submit" name="button"><i class="fa fa-trash"></i></button>
            </form>
          </td>
        </tr>
      @empty
        <tr>
          <td colspan="3" class="text-center"><h2>Данные отсутствуют</h2></td>
        </tr>
      @endforelse
    </tbody>
    <tfoot>
      <tr>
        <td colspan="3">
          <ul class="pagination float-end">
            {{$articles->links()}}
          </ul>
        </td>
      </tr>
    </tfoot>
  </table>
</div>

@endsection